AllCops:
  Include:
    - '**/Gemfile'
    - '**/*.rb'
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120

Lint/SuppressedException:
  Enabled: false

Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Max: 100
Metrics/ClassLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/ParallelAssignment:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
